#pragma once

typedef enum MouseCode
{
	// From glfw3.h
	LSH_MOUSE_BUTTON0 = 0,
	LSH_MOUSE_BUTTON1 = 1,
	LSH_MOUSE_BUTTON2 = 2,
	LSH_MOUSE_BUTTON3 = 3,
	LSH_MOUSE_BUTTON4 = 4,
	LSH_MOUSE_BUTTON5 = 5,
	LSH_MOUSE_BUTTON6 = 6,
	LSH_MOUSE_BUTTON7 = 7,

	LSH_MOUSE_BUTTON_LAST = LSH_MOUSE_BUTTON7,
	LSH_MOUSE_BUTTON_LEFT = LSH_MOUSE_BUTTON0,
	LSH_MOUSE_BUTTON_RIGHT = LSH_MOUSE_BUTTON1,
	LSH_MOUSE_BUTTON_MIDDLE = LSH_MOUSE_BUTTON2
} MouseCode;